package com.mycompany.backenddynamodb.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.Data;

@Data
@DynamoDBTable(tableName = "tb_alumnos")
public class alumno {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String idAlumno;

    @DynamoDBAttribute
    private String anio;
    @DynamoDBAttribute
    private String apellido;
    @DynamoDBAttribute
    private String codigoCarrera;
    @DynamoDBAttribute
    private String correlativo;
    @DynamoDBAttribute
    private String correo;
    @DynamoDBAttribute
    private String nombre;
}
